### ISSUE TITLE
 Execute on multiremote mode

### ISSUE THREAD

**Issue by gabynicora** [wswebcreation/wdio-ocr-service#8]
**Is your feature request related to a problem? Please describe.**
We execute multiremote mode (android 11 real device and chrome on mac big sur) and need OCR recognition on both driver,
When BEFORE hook execute calls to this service function and pass DRIVER object. OcrService.prototype.before = function (caps, specs, driver).
The problem its the driver itself, in multiremote driver is an array of drivers.

**Describe the solution you'd like**
By default I would not make any changes, but I would modify the call in the before hook to be able to indicate which driver it has to work with, just as optional setting.

**Describe alternatives you've considered**
Use a forech loop to execute function updateSettings and any other function executed on before hook,

**Additional context**
This is the error we get.
@wdio/utils:shim: TypeError: this._driver.updateSettings is not a function
[0-0]     at OcrService.<anonymous> (/Users/gnicora/repos/automation-mobile/node_modules/wdio-ocr-service/build/service.js:68:59)
[0-0]     at step (/Users/gnicora/repos/automation-mobile/node_modules/wdio-ocr-service/build/service.js:33:23)
[0-0]     at Object.next (/Users/gnicora/repos/automation-mobile/node_modules/wdio-ocr-service/build/service.js:14:53)
[0-0]     at /Users/gnicora/repos/automation-mobile/node_modules/wdio-ocr-service/build/service.js:8:71
[0-0]     at new Promise (<anonymous>)
[0-0]     at __awaiter (/Users/gnicora/repos/automation-mobile/node_modules/wdio-ocr-service/build/service.js:4:12)
[0-0]     at OcrService.before (/Users/gnicora/repos/automation-mobile/node_modules/wdio-ocr-service/build/service.js:59:16)
[0-0]     at /Users/gnicora/repos/automation-mobile/node_modules/@wdio/utils/build/shim.js:82:27
[0-0]     at new Promise (<anonymous>)
[0-0]     at /Users/gnicora/repos/automation-mobile/node_modules/@wdio/utils/build/shim.js:79:47
[0-0]     at Array.map (<anonymous>)
[0-0]     at executeHooksWithArgsShim (/Users/gnicora/repos/automation-mobile/node_modules/@wdio/utils/build/shim.js:79:33)
[0-0]     at Runner.run (/Users/gnicora/repos/automation-mobile/node_modules/@wdio/runner/build/index.js:99:48)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)

We use
 node 14.17.0
and our package.json is this:
"devDependencies": {
    "@babel/plugin-syntax-class-properties": "^7.10.1",
    "@babel/plugin-transform-classes": "^7.10.3",
    "@babel/plugin-transform-computed-properties": "^7.10.3",
    "@babel/preset-env": "^7.10.3",
    "@babel/register": "^7.10.3",
    "@types/chai": "^4.2.11",
    "@types/node": "^14.0.14",
    "@wdio/appium-service": "^7.16.3",
    "@wdio/browserstack-service": "^7.16.3",
    "@wdio/cli": "^7.6.1",
    "@wdio/cucumber-framework": "7.16.3",
    "@wdio/junit-reporter": "^7.16.3",
    "@wdio/local-runner": "^7.16.3",
    "@wdio/reporter": "^7.16.3",
    "@wdio/spec-reporter": "^7.16.3",
    "babel-eslint": "^10.1.0",
    "env-cmd": "^10.1.0",
    "node-fetch": "^2.6.0",
    "ts-node": "^8.10.2",
    "typescript": "^3.9.5",
    "wdio-chromedriver-service": "^7.1.0",
    "webdriverio": "^7.16.3"
  },
  "dependencies": {
    "@wdio/codemod": "^0.9.0",
    "appium": "1.21.0",
    "axios": "^0.19.2",
    "base-64": "^0.1.0",
    "chromedriver": "^95.0.0",
    "dotenv": "^8.2.0",
    "jscodeshift": "^0.12.0",
    "lodash": "^4.17.15",
    "tesseract.js": "^2.1.4",
    "wdio-ocr-service": "^1.1.0"
  }

SORRY FOR MY BAD ENGLISH.

**Comment by wswebcreation** [comment]
Hi @gabynicora 

This OCR service doesn't support Multiremote (yet)

**Comment by gabynicora** [comment]
OK thanks, i wait for multiremote version.
